### PR TITLE
Enhance Scrambled_Macro and place script to install powershell in kali

### PR DESCRIPTION
**Pull request by ceramicskate0**
Fix issue with powershell not working in kali via script and enhance scrambled_macro stager.

### CODE REVIEW

**Comment by cobbr** [comment]
Hi @ceramicskate0 , thanks for the pull request. I'll definitely take a look at the script you put together for installing/fixing PowerShell in Kali.

I'm a little confused what you are trying to accomplish with the Scrambled_Macro stager. It looks like you took out obfuscation and added some enhancements to the stager itself?

**Comment by ceramicskate0** [comment]
That was an oversight I will correct the stager to match ObfuscatedEmpire and not base empire

**Comment by cobbr** [comment]
What exactly are the improvements you are making to the Scrambled_Macro stager? Does it affect the obfuscation that was added in ObfuscatedEmpire?

I only ask because the Scrambled_Macro changes might best be made as a Pull Request to the main Empire project.

**Comment by ceramicskate0** [comment]
Agreed i think changes to Scrambled_Macro should be a pull to main Empire.

The changes to Scrambled_Macro took the variables and method names used in the generated macro code and made them randomly named which had success in AV bypass for some vendors. However, i think the obfuscation used in ObfuscatedEmpire will accomplish the same thing with better results.

**Pull request closed without merging**
